### ISSUE TITLE
[3.1.0] Security problem NULL DT_RUNPATH

### ISSUE THREAD

**Issue by RarogCmex** [RadeonOpenCompute/atmi#11]
Gentoo Linux QA system is detect error when I tries to create own ebuild
scanelf: rpath_security_checks(): Security problem NULL DT_RUNPATH in /var/tmp/portage/dev-libs/atmi-3.1.0/image/usr/lib64/libatmi_runtime.so.0.7.0
Auto fixing rpaths for /var/tmp/portage/dev-libs/atmi-3.1.0/image/usr/lib64/libatmi_runtime.so.0.7.0

 * QA Notice: The following files contain insecure RUNPATHs
 *  Please file a bug about this at https://bugs.gentoo.org/
 *  with the maintainer of the package.
 *   /var/tmp/portage/dev-libs/atmi-3.1.0/image/usr/lib64/libatmi_runtime.so.0.7.0
 *     RPATH: :$ORIGIN:$ORIGIN/../../hsa/lib:$ORIGIN/../../lib
 *

**Comment by estewart08** [comment]
I am not familiar with gentoo and ebuild. I assume you are building from atmi from source? If so, are you able to specify a specific branch for the atmi repo to test in the ebuild?

**Comment by RarogCmex** [comment]
@estewart08 
Yes, I could.
Thank you, that branch fixes the issue.

**Comment by RarogCmex** [comment]
We are using folowing cmake hint to make it build 
[atmi-3.0.0-cmake_library_hint.patch.zip](https://github.com/RadeonOpenCompute/atmi/files/4291587/atmi-3.0.0-cmake_library_hint.patch.zip)
So possibly I should ask you also about official bypass... But that's another story, I can't working under that at this moment. 
Have a nice day!

**Comment by RarogCmex** [comment]
I hope I'll mainline ATMI in Gentoo.
