### ISSUE TITLE
ATMI not supported on AArch64

### ISSUE THREAD

**Issue by lintcoder** [RadeonOpenCompute/atmi#2]
I am trying to build ROCm from branch roc-1.6.3 on my ubunu16.04-arm64 server which is running on Cavium Thunder X. Now I have built ROCK-Kernel-Driver, ROCT-Thunk-Interface and ROCR-Runtime, HCC as well as HIP. When it comes to atmi, I follow the step in INSTALL.md:
1.cd src
2.mkdir build && cd build
3.cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm/atmi ..
output of cmake as follows:
-- ATMI: Not building ATMI Runtime: only support ATMI in Linux x86_64 or ppc64le hosts.
-- ATMI: Not building ATMI C Extension: only support ATMI in Linux x86_64 or ppc64le hosts.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cavium/rocm/atmi/src/build

From the output, it seems that ATMI is not supported on aarch64, besides, make command gives nothing output. 
@ashwinma

**Comment by ashwinma** [comment]
I have not tested on aarch64, but please feel free to edit src/runtime/CMakeLists.txt:18 and try it out. Let me know if it works or not. 
```
diff --git a/src/runtime/CMakeLists.txt b/src/runtime/CMakeLists.txt
index 16c165a..e3a55f8 100644
--- a/src/runtime/CMakeLists.txt
+++ b/src/runtime/CMakeLists.txt
@@ -15,7 +15,7 @@
 #

 if(ATMI_DEP_LIBHSA_FOUND)
-    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(x86_64)|(ppc64le)$" AND CMAKE_SYSTEM_NAME MATCHES "Linux")
+    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(aarch64)|(x86_64)|(ppc64le)$" AND CMAKE_SYSTEM_NAME MATCHES "Linux")
         libatmi_runtime_say("Preparing to build runtime/core")
         add_subdirectory(core)
         add_subdirectory(interop)
```

**Comment by ashwinma** [comment]
This should be supported from v0.7
