### ISSUE TITLE
fix device type value

### ISSUE THREAD

**Issue by louishp** [RadeonOpenCompute/atmi#20]
atmi_machine_t use the value of ATMI_DEVTYPE_ALL to define device_count_by_type and devices_by_type to maintain the munber of different devices, but ATMI_DEVTYPE_ALL is defined as 0x1111, however this value is 4369. I think you just want to use binary bits to indicate the type of each device.

**Comment by ashwinma** [comment]
Thanks for the catch and the fix. This will be merged soon.

**Comment by ashwinma** [comment]
Resolved in #19
