### ISSUE TITLE
Atmi revision number wrong for Apt/Dpkg

### ISSUE THREAD

**Issue by reanimastudios** [RadeonOpenCompute/atmi#6]
atmi_0.0.1-_amd64.deb

The revision number is invalid, but you released it anyways on August 10, 2019. 

http://repo.radeon.com/rocm/apt/debian/pool/main/a/atmi/

A rather absurd and unprofessional Software Quality Assurance/Build Harness review I might add.

**Comment by ashwinma** [comment]
We would love to know about any technical feedback you may have from using ATMI -- what you use it for and how we can improve it? 

The above issue is known and we are fixing it for our next release. Thanks for the kind feedback.

**Comment by ashwinma** [comment]
Fixed
